# Generated by Django 6.0.5 on 2026-06-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0, help_text='1 point = ₹1 discount. Earned on confirmed bookings.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marketing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='newsletter_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'हिन्दी (Hindi)'), ('Spanish', 'Español (Spanish)'), ('French', 'Français (French)'), ('German', 'Deutsch (German)')], default='English', max_length=20),
        ),
    ]
